const types = Object.freeze({
    SET_TASKS: "SET_TASKS",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL_TASKS: "TOGGLE_CHECK_ALL_TASKS",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    //Contact Form
    ADD_CONTACT_FORM: "ADD_CONTACT_FORM",
    CHANGE_CONTACT_FORM: "CHANGE_CONTACT_FORM",
    TOGGLE_CONTACT_LOADING: "TOGGLE_CONTACT_LOADING",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    //Single Task
    TOGGLE_ST_LOADING: "TOGGLE_ST_LOADING",
    SET_ST: "SET_ST",
    TOGGLE_ST_MODAL: "TOGGLE_ST_MODAL",
    TOGGLE_ST_CONFIRM_MODAL: "TOGGLE_ST_CONFIRM_MODAL",
    
});
export default types;