const types = Object.freeze({
    SET_TASKS: "SET_TASKS",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL_TASKS: "TOGGLE_CHECK_ALL_TASKS",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    SET_MSG: "SET_MSG",
    TOGGLE_STATUS_TASK: "TOGGLE_STATUS_TASK",
    //Contact Form
    ADD_CONTACT_FORM: "ADD_CONTACT_FORM",
    CHANGE_CONTACT_FORM: "CHANGE_CONTACT_FORM",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    //Single Task
    TOGGLE_ST_LOADING: "TOGGLE_ST_LOADING",
    SET_ST: "SET_ST",
    TOGGLE_ST_MODAL: "TOGGLE_ST_MODAL",
    TOGGLE_ST_CONFIRM_MODAL: "TOGGLE_ST_CONFIRM_MODAL",
    //Filter
    SET_STATUS: "SET_STATUS",
    CHANGE_SEARCH_VALUE: "CHANGE_SEARCH_VALUE",
    SET_SORT_DATE: "SET_SORT_DATE",
    RESET_SEARCH_FORM: "RESET_SEARCH_FORM",

});
export default types;