const types = Object.freeze({
    SET_TASKS: "SET_TASKS",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL_TASKS: "TOGGLE_CHECK_ALL_TASKS",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL"

});
export default types;